version: '3'
services:

  config:
    image: valeryvalavitski/config:1.0
    container_name: config
    environment:
      SPRING_CLOUD_CONFIG_SERVER_GIT_URI: https://github.com/cmunknown/spring-cloud-config-server
#      SPRING_CLOUD_CONFIG_SERVER_GIT_CLONE_ON_START: "true"
#      SPRING_CLOUD_CONFIG_SERVER_GIT_PASSWORD: ""
    ports:
      - '8888:8888'

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    depends_on:
      - config

  kafka:
    image: confluentinc/cp-kafka:latest
    hostname: kafka
    depends_on:
      - zookeeper
      - config
    ports:
      - '9092:9092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:9092'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
#
  kafkaproducer:
    image: valeryvalavitski/kafkaproducer:1.0
    container_name: kafkaproducer
    environment:
#      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_CLOUD_CONFIG_URI: http://config:8888
    depends_on:
      - zookeeper
      - kafka
      - config
    ports:
      - "8080:8080"
    restart: always

  kafkaconsumer:
    image: valeryvalavitski/kafkaconsumer:1.0
    container_name: kafkaconsumer
    environment:
#      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_CLOUD_CONFIG_URI: http://config:8888
    depends_on:
      - zookeeper
      - kafka
      - kafkaproducer
      - config
    ports:
      - "8081:8080"
    restart: always

  ibm:
    image: ibmcom/mq:latest
    container_name: mqserver
    ports:
      - "1414:1414"
      - "9443:9443"
    hostname: ibm
    environment:
      - LICENSE=accept

  ibmproducer:
    image: valeryvalavitski/ibmproducer:5.0
    container_name: ibmproducer
    environment:
#      PROJECT.MQ.PORT: 1414
#      PROJECT.MQ.HOST: ibm
      LICENSE: accept
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
#      SPRING_CLOUD_CONFIG_URI: http://config:8888

    depends_on:
      - zookeeper
      - kafka
      - kafkaconsumer
      - kafkaproducer
      - ibm
      - config
    ports:
      - "8082:8080"